# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'KuaiYiSuper' do

pod ‘AFNetworking’, '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'Masonry', '~> 1.0.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'FMDB', '~> 2.6.2'
pod 'SVProgressHUD', '~> 2.0.3'

end

